FROM ubuntu:latest

COPY requirements.txt requirements.txt
COPY generate_certs.py generate_certs.py
COPY conf.yml conf.yml

RUN apt update && apt install python3 python3-pip certbot python3-certbot-nginx -y 
RUN python3 -m pip install -r requirements.txt --break-system-packages
CMD python3 generate_certs.py