FROM nginx:latest

COPY requirements.txt requirements.txt
COPY generate_nginx_conf.py generate_nginx_conf.py
COPY conf.yml conf.yml
COPY base_nginx.conf base_nginx.conf

RUN apt update && apt install python3 python3-pip -y
RUN python3 -m pip install -r requirements.txt --break-system-packages

CMD python3 generate_nginx_conf.py && nginx -g "daemon off;"
